import fs from 'node:fs/promises';
const str={type:'string'},bool={type:'boolean'},integer={type:'integer',minimum:0},id={type:'string',format:'uuid'},date={type:'string',format:'date-time'},nullable=s=>({anyOf:[s,{type:'null'}]}),array=items=>({type:'array',items}),ref=name=>({$ref:`#/components/schemas/${name}`});
const object=(properties,required=Object.keys(properties),additionalProperties=true)=>({type:'object',properties,required,additionalProperties});
const hash={type:'string',pattern:'^[a-f0-9]{64}$'},graph=object({nodes:array({type:'object'}),edges:array({type:'object'})}),config={type:'object',description:'Canonical Vector configuration; unknown properties are preserved. Secrets and unsafe capabilities are validated independently.'};
const configurationMode={enum:['restricted','full'],description:'Locally granted capability profile reported by the device; omission means restricted. Never writable through remote policy.'};
const variableDeclarations={type:'array',maxItems:64,items:ref('VariableDeclaration'),description:'Draft-owned nonsecret scalar replacement slots, captured immutably in each published version. Paths are canonical RFC6901 pointers to existing leaves; server validation rejects structural and known credential fields and rechecks each rendered configuration against target capabilities.'};
const variableValues={type:'object',propertyNames:{pattern:'^[A-Za-z][A-Za-z0-9_]{0,63}$'},additionalProperties:{oneOf:[{type:'string',maxLength:4096,description:'Server also limits UTF-8 encoding to 4096 bytes.'},{type:'integer',minimum:-9007199254740991,maximum:9007199254740991},{type:'boolean'}]},description:'Values must exactly match published declaration names and types. Missing, extra, and secret-like values are rejected by the server.'};
const configurationAttemptState={enum:['desired','downloaded','validated','written','reload_requested','verified_applied','verification_unknown','failed','rolled_back','paused']};
const configurationAttempt=object({generation:{type:'integer',minimum:1,maximum:9007199254740991},version_id:id,sha256:hash,secret_revision:{type:'integer',minimum:0,maximum:9007199254740991},state:configurationAttemptState,error:object({code:{type:'string',minLength:1,maxLength:128},stage:{type:'string',minLength:1,maxLength:128},message:{type:'string',maxLength:1000}},undefined,false)},['generation','version_id','sha256','state'],false);
const metric=nullable({type:'number',minimum:0,maximum:1e15});
const componentMetric=object({id:{type:'string',maxLength:100},type:{type:'string',maxLength:100},events_per_second:metric,errors:metric,discarded_events:metric,buffer_bytes:metric},['id'],false);
const revisionNumber={type:'integer',minimum:1};
const pageNumber={type:'integer',minimum:1,maximum:9007199254740991};
const pipelineRequestOrigins=[{properties:{operation:{const:'create'},source_configuration_id:{type:'null'},source_revision:{type:'null'}}},{properties:{operation:{const:'duplicate'},source_configuration_id:id,source_revision:pageNumber}}];
const provenance=object({kind:{enum:['draft','revision','version']},id,revision:revisionNumber},['kind','id']);
const revisionMetadata={id,configuration_id:id,revision:revisionNumber,name:str,description:str,message:str,created_at:date,author:str,author_id:id,archived:bool,source:provenance};
const versionMetadata={id,configuration_id:id,number:revisionNumber,sha256:hash,size:integer,created_at:date,message:str,uses_local_secrets:bool,author:str,author_id:id,source_revision:revisionNumber};
const metadataOnly={not:{anyOf:['config','graph','variables','artifact','validation'].map(key=>({required:[key]}))}};
const deploymentStatus={enum:['scheduled','active','paused','completed','cancelled','failed','missed','unassigned']};
const requestSummary={request_id:id,deployment_id:id,created_at:date,deployment_name:nullable({type:'string',maxLength:120}),deployment_status:nullable({type:'string',maxLength:64}),configuration_name:nullable({type:'string',maxLength:240}),version_number:nullable({type:'integer',minimum:1,maximum:9007199254740991}),resource:{enum:['configuration','policy']},scheduled_at:nullable(date)};
const bounded=n=>({type:'string',maxLength:n}),auditInteger={type:'integer',minimum:0,maximum:9007199254740991};
const auditSummary={id:bounded(128),actor_id:bounded(128),actor:bounded(256),actor_kind:{enum:['user','device','system','unknown']},action:bounded(128),target:bounded(256),target_id:nullable(bounded(256)),target_kind:{enum:['user','device','configuration','deployment','group','policy','token','issue','signing_key','server','unknown']},target_name:nullable(bounded(256)),device_id:nullable(bounded(128)),outcome:bounded(128),created_at:nullable(date),request_id:nullable(bounded(128))};
const auditDetails={reason:bounded(1000),previous_group_revision:auditInteger,group_revision:auditInteger,issue_revision:auditInteger,secret_revision:auditInteger,previous_secret_revision:auditInteger,actual_sha256:hash,applied_template_sha256:hash,device_id:bounded(128),previous_generation:auditInteger,generation:auditInteger,previous_policy_generation:auditInteger,policy_generation:auditInteger,secret_revision_floor:auditInteger,version_id:bounded(128),sha256:hash,policy_sha256:hash,browser_sessions:auditInteger,password_reset_codes:auditInteger,enrollment_tokens_to_revoke:auditInteger,mfa_recovery_codes:auditInteger,previous_device_id:id,replacement_device_id:id,deployment_id:id,previous_signing_key_id:hash,signing_key_id:hash};
const auditFilters={search:bounded(200),action:{type:'string',maxLength:128,pattern:'^[A-Za-z0-9_.-]*$'},family:{type:'string',maxLength:128,pattern:'^[A-Za-z0-9_.-]*$'},outcome:{type:'string',maxLength:128,pattern:'^[A-Za-z0-9_.-]*$'},actor_id:bounded(128),device_id:id,target_id:bounded(256),from:date,to:date};
const schemas={
 VariableDeclaration:object({name:{type:'string',pattern:'^[A-Za-z][A-Za-z0-9_]{0,63}$'},path:{type:'string',minLength:2,maxLength:512,pattern:'^/'},type:{enum:['string','integer','boolean']}},undefined,false),
 VariableBindings:object({defaults:variableValues,devices:{type:'object',propertyNames:{format:'uuid'},additionalProperties:variableValues}},['defaults','devices'],false),
 ArtifactPreview:object({device_id:id,sha256:hash,size:{type:'integer',minimum:1,maximum:1048576}},undefined,false),
 ConfigurationAttempt:configurationAttempt,
 AuditSummary:object({...auditSummary,target_exists:bool},Object.keys(auditSummary),false),
 AuditDetail:object({...auditSummary,target_exists:bool,details:object(auditDetails,[],false)},[...Object.keys(auditSummary),'details'],false),
 AuditHistoryPage:object({items:{type:'array',maxItems:50,items:ref('AuditSummary')},total:auditInteger,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 AuditExportFilters:object(auditFilters,[],false),
 AuditExport:object({id,filters:ref('AuditExportFilters'),row_count:{type:'integer',minimum:0,maximum:100000},byte_count:{type:'integer',minimum:0,maximum:134217728},sha256:hash,created_at:date,expires_at:date,download_path:{type:'string',pattern:'^/api/v1/audit/exports/[0-9a-f-]+/download$'}},undefined,false),
 Error:object({error:object({code:str,message:str})}),
 User:object({id,email:{type:'string',format:'email'},name:str,role:{enum:['viewer','editor','operator','admin']},enabled:bool,revision:{type:'integer',minimum:1}}),
 AccessEditReceipt:object({request_id:id,user:ref('User')},undefined,false),
 AccessEditResult:{oneOf:[ref('User'),ref('AccessEditReceipt')]},
 AccessEditRequestStatus:{oneOf:[object({request_id:id,user_id:id,status:{const:'not_found'}},undefined,false),object({request_id:id,user_id:id,status:{const:'cancelled'}},undefined,false),object({request_id:id,user_id:id,status:{const:'applied'},user:ref('User')},undefined,false)],description:'Actor-scoped exact-target access edit status. An applied user is the immutable public commit snapshot, not necessarily the account’s current state. not_found is noncausal while a PUT may be in flight; cancellation fences only an absent request and cannot undo an applied edit.'},
 UserCreateReceipt:object({request_id:id,user:ref('User')},undefined,false),
 UserCreateResult:{oneOf:[ref('User'),ref('UserCreateReceipt')]},
 UserRequestStatus:{oneOf:[object({request_id:id,status:{const:'not_found'}},undefined,false),object({request_id:id,status:{const:'cancelled'}},undefined,false),object({request_id:id,status:{const:'created'},user:ref('User')},undefined,false)],description:'Actor-scoped, secret-free current status. not_found is not cancellation: an in-flight POST may still commit. A repeated keyed POST always conflicts; cancel fences a late create only when it wins the writer transaction.'},
 ResetIssueReceipt:object({request_id:id,user_id:id,code:{type:'string',pattern:'^[a-f0-9]{64}$'},expires_at:date},undefined,false),
 ResetIssueResult:{oneOf:[object({code:{type:'string',pattern:'^[a-f0-9]{64}$'},expires_at:date},undefined,false),ref('ResetIssueReceipt')]},
 ResetRequestStatus:{oneOf:[object({request_id:id,user_id:id,status:{const:'not_found'}},undefined,false),object({request_id:id,user_id:id,status:{const:'issued'},active:bool,expires_at:date},undefined,false),object({request_id:id,user_id:id,status:{const:'cancelled'},was_issued:bool},undefined,false)],description:'Actor-scoped, exact-target, secret-free reset issuance status. A negative read does not fence an in-flight POST. Issued active is true only while this exact code verifier remains current and unexpired for an enabled account. Cancellation revokes the exact still-current unused code and fences late issuance; it cannot undo a code already redeemed.'},
 Session:object({user:ref('User'),csrf_token:str}),
 LoginChallenge:object({mfa_required:{const:true},challenge_token:{type:'string',pattern:'^[a-f0-9]{64}$'},expires_at:date},undefined,false),
 LoginResult:{oneOf:[ref('Session'),ref('LoginChallenge')]},
 Status:object({initialized:bool,version:str}),
 Configuration:object({id,name:str,description:str,revision:integer,graph,config,variables:variableDeclarations,created_at:date,updated_at:date,archived:{type:'boolean',default:false,description:'Organization/editing state only. Archived drafts cannot be saved, restored or published; all immutable versions remain readable and deployable.'},archived_at:{...nullable(date),default:null}},['id','name','description','revision','graph','config','variables','created_at','updated_at']),
 PipelineCreateReceipt:{allOf:[ref('Configuration'),object({request_id:id,revision:pageNumber,archived:bool,archived_at:nullable(date)},undefined)]},
 PipelineRequestLookup:{oneOf:[object({request_id:id,found:{const:false}},undefined,false),{...object({request_id:id,found:{const:true},operation:{enum:['create','duplicate']},source_configuration_id:nullable(id),source_revision:nullable(pageNumber),configuration:ref('PipelineCreateReceipt')},undefined,false),oneOf:pipelineRequestOrigins}],description:'Nested request_id must equal the outer key. A duplicate result UUID must differ from its source. Current result contents may have changed since creation; original operation/source metadata remains immutable.'},
 PipelineRequestPage:object({items:{type:'array',maxItems:50,items:{...object({request_id:id,operation:{enum:['create','duplicate']},source_configuration_id:nullable(id),source_revision:nullable(pageNumber),configuration_id:id,configuration_name:nullable(bounded(240)),created_at:date},undefined,false),oneOf:pipelineRequestOrigins}},total:auditInteger,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 ConfigurationLibraryItem:object({id,name:str,description:str,revision:revisionNumber,created_at:date,updated_at:date,archived:bool,archived_at:nullable(date),component_counts:object({sources:integer,transforms:integer,sinks:integer},undefined,false),latest_version:nullable(object({id,number:revisionNumber,created_at:date},undefined,false))},undefined,false),
 ConfigurationLibraryPage:object({items:{type:'array',maxItems:50,items:ref('ConfigurationLibraryItem')},total:integer,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 Activity:object({id,actor:str,actor_id:str,actor_kind:auditSummary.actor_kind,action:str,target:str,target_name:nullable(str),target_id:nullable(str),target_kind:auditSummary.target_kind,target_exists:bool,outcome:str,created_at:nullable(date)},['id','actor','action','target','outcome','created_at']),
 Issue:object({id:hash,device_id:id,device_name:nullable(str),device_revoked:nullable(bool),code:str,stage:str,message:str,count:integer,first_seen:nullable(date),last_seen:nullable(date),desired_version_id:nullable(str),resolved:bool,revision:pageNumber,acknowledged:bool,acknowledged_at:nullable(date),acknowledged_by:nullable(str),acknowledged_by_name:nullable(str),acknowledgement_reason:nullable({type:'string',maxLength:1000}),disposition:{enum:['open','acknowledged','resolved']}},undefined,false),
 IssueHistoryPage:object({items:{type:'array',maxItems:50,items:ref('Issue')},total:integer,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 Overview:object({devices_total:integer,devices_online:integer,configurations_total:integer,deployments_active:integer,issues_open:integer,devices:array(ref('Device')),recent_activity:{type:'array',maxItems:20,items:ref('Activity')}}),
 Revision:object({...revisionMetadata,graph,config,variables:variableDeclarations},['id','configuration_id','revision','graph','config','variables','message','created_at','author']),
 RevisionMetadata:{...object(revisionMetadata,['id','configuration_id','revision','message','created_at','author']),...metadataOnly},
 Version:object({...versionMetadata,graph,config,variables:variableDeclarations,artifact:str,validation:{type:'object'}},['id','configuration_id','number','graph','config','variables','artifact','sha256','size','created_at','message','validation']),
 PublishReceipt:object({...versionMetadata,number:pageNumber,source_revision:pageNumber,request_id:id,graph,config,variables:variableDeclarations,artifact:str,validation:{type:'object'}},['id','configuration_id','number','source_revision','request_id','graph','config','variables','artifact','sha256','size','created_at','message','validation']),
 PublishRequestLookup:{oneOf:[object({request_id:id,found:{const:false}},undefined,false),object({request_id:id,found:{const:true},version:ref('PublishReceipt')},undefined,false)]},
 PublishRequestPage:object({items:{type:'array',maxItems:50,items:object({request_id:id,configuration_id:id,version_id:id,number:pageNumber,source_revision:pageNumber,created_at:date},undefined,false)},total:auditInteger,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 VersionMetadata:{...object(versionMetadata,['id','configuration_id','number','sha256','size','created_at','message']),...metadataOnly},
 HistoryPage:object({items:{type:'array',maxItems:50,items:{oneOf:[ref('RevisionMetadata'),ref('VersionMetadata')]}},total:integer,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}}),
 AgentPolicy:object({heartbeat_seconds:{type:'integer',minimum:10,maximum:3600},sync_paused:bool,telemetry_enabled:bool},undefined,false),
 SavedPolicy:object({id,name:{type:'string',minLength:1,maxLength:120,description:'Nonempty, at most 120 UTF-8 bytes, with no NUL character. The byte bound is enforced by the server and dashboard.'},policy:ref('AgentPolicy'),created_at:date},undefined,false),
 PolicyCreateReceipt:object({id,name:{type:'string',minLength:1,maxLength:120},policy:ref('AgentPolicy'),created_at:date,request_id:id,create_idempotency:{const:true}},undefined,false),
 PolicyRequestLookup:{oneOf:[object({create_idempotency:{const:true},request_id:id,found:{const:false}},undefined,false),object({create_idempotency:{const:true},request_id:id,found:{const:true},policy:ref('PolicyCreateReceipt')},undefined,false)],description:'The outer request identity must match the nested receipt and the expected actor-scoped request. A negative read does not prove an in-flight request cannot still commit.'},
 PolicyRequestPage:object({create_idempotency:{const:true},items:{type:'array',maxItems:50,items:object({request_id:id,policy_id:id,policy_name:nullable({type:'string',maxLength:120}),created_at:date},undefined,false)},total:auditInteger,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 Selector:object({device_ids:array(id),group_ids:array(id),exclude_ids:array(id)}),
 Rollout:object({kind:{enum:['all','canary']},canary_size:{type:'integer',minimum:1},batch_size:{type:'integer',minimum:1},observation_seconds:{type:'integer',minimum:0},failure_threshold:integer}),
 Telemetry:object({sampled_at:date,events_per_second:metric,errors:metric,uptime_seconds:metric,memory_bytes:metric,cpu_seconds:metric,discarded_events:metric,buffer_bytes:metric,components:{type:'array',maxItems:50,items:componentMetric}},['sampled_at']),
 TelemetryHistory:object({device_id:id,samples:array(ref('Telemetry'))}),
 Assignment:object({id,priority:{type:'integer',minimum:-1000000,maximum:1000000},reason:str}),
 Device:object({id,name:str,configuration_mode:configurationMode,effective_policy:ref('AgentPolicy'),assignment:ref('Assignment'),policy_assignment:ref('Assignment'),os:str,arch:str,agent_version:str,vector_version:str,status:str,apply_state:str,desired_generation:integer,reported_generation:integer,last_seen:nullable(date),desired_version_id:nullable(id),actual_sha256:nullable(hash),applied_template_sha256:nullable(hash),secret_revision:integer,uses_local_secrets:bool,local_paused:bool,labels:{type:'object'},sync_paused:bool,pause_acknowledged:bool,telemetry:nullable(ref('Telemetry')),created_at:date},['id','name','status','apply_state','desired_generation','reported_generation']),
 DeploymentTarget:object({device_id:id,state:str,generation:integer,error:nullable(str)},['device_id','state','generation']),
 Deployment:object({id,version_id:nullable(id),policy:nullable(ref('AgentPolicy')),selector:ref('Selector'),priority:{type:'integer'},target_mode:{enum:['snapshot','persistent']},status:{enum:['scheduled','active','paused','completed','cancelled','failed','missed','unassigned']},scheduled_at:nullable(date),created_at:date,targets:array(ref('DeploymentTarget')),rollout:ref('Rollout')},['id','selector','priority','target_mode','status','created_at','targets','rollout']),
 DeploymentSummary:object({id,name:nullable({type:'string',maxLength:120}),configuration_id:nullable(id),configuration_name:nullable(str),version_id:nullable(id),version_number:nullable(revisionNumber),policy:nullable(ref('AgentPolicy')),priority:{type:'integer'},target_mode:{enum:['snapshot','persistent']},status:deploymentStatus,scheduled_at:nullable(date),created_at:date,rollout:ref('Rollout'),target_count:integer,verified_count:integer,state_counts:{type:'object',additionalProperties:integer}},undefined,false),
 DeploymentHistoryPage:object({items:{type:'array',maxItems:50,items:ref('DeploymentSummary')},total:integer,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 DeploymentTargetSummary:object({device_id:id,device_name:nullable(str),state:str,generation:integer,error:nullable(str),original:bool},undefined,false),
 DeploymentTargetPage:object({items:{type:'array',maxItems:50,items:ref('DeploymentTargetSummary')},total:integer,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 DeploymentRequest:object({request_id:{...id,description:'Optional durable create identity scoped to the authenticated actor. Reuse only with the identical payload.'},name:nullable({type:'string',maxLength:120}),version_id:id,policy:ref('AgentPolicy'),variable_bindings:ref('VariableBindings'),selector:ref('Selector'),expected_device_ids:array(id),priority:{type:'integer'},target_mode:{enum:['snapshot','persistent']},scheduled_at:nullable(date),rollout:ref('Rollout')},['selector','priority','target_mode','rollout'],false),
 DeploymentReceipt:{allOf:[ref('Deployment'),object({request_id:id,operation:{enum:['create','rollback']},source_deployment_id:nullable(id),request_correlation:{const:true}})],oneOf:[{properties:{operation:{const:'create'},source_deployment_id:{type:'null'}}},{properties:{operation:{const:'rollback'},source_deployment_id:id}}],description:'Current original result with response-only durable request identity. For rollback, result ID differs from source ID. Mutable deployment state and targets need not equal the original request.'},
 DeploymentRequestStatus:{oneOf:[object({request_id:id,found:{const:false}},undefined,false),object({request_id:id,found:{const:true},operation:{const:'create'},source_deployment_id:{type:'null'},deployment:ref('DeploymentReceipt')},undefined,false),object({request_id:id,found:{const:true},operation:{const:'rollback'},source_deployment_id:id,deployment:ref('DeploymentReceipt')},undefined,false)],description:'Outer request_id, operation and source_deployment_id must exactly match the nested receipt and the locally frozen operation. A negative read is not proof an in-flight request failed.'},
 DeploymentRequestSummary:{oneOf:[object({...requestSummary,operation:{const:'create'},source_deployment_id:{type:'null'}},undefined,false),object({...requestSummary,operation:{const:'rollback'},source_deployment_id:id},undefined,false)]},
 DeploymentRequestPage:object({items:{type:'array',maxItems:50,items:ref('DeploymentRequestSummary')},total:{type:'integer',minimum:0,maximum:9007199254740991},page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 PreviewOutcome:object({device_id:id,resource:{enum:['configuration','policy']},outcome:{enum:['requested','higher_priority','conflict']},assignment:ref('Assignment')},['device_id','resource','outcome']),
 PreviewBlocker:{oneOf:[object({deployment_id:id,device_ids:array(id),resource:{enum:['configuration','policy']},code:{const:'ACTIVE_CANARY_OVERLAP'},reason:str},undefined,false),object({device_ids:array(id),resource:{const:'configuration'},code:{enum:['FULL_VECTOR_MODE_REQUIRED','VECTOR_VERSION_INCOMPATIBLE']},reason:str},undefined,false)]},
 Preview:object({devices:array(ref('Device')),conflicts:array({}),warnings:array(str),outcomes:array(ref('PreviewOutcome')),artifact_previews:array(ref('ArtifactPreview')),create_idempotency:{const:true},blockers:array(ref('PreviewBlocker'))},['devices','conflicts','warnings','outcomes']),
 Group:object({id,name:str,description:str,device_ids:array(id),revision:{type:'integer',minimum:0,maximum:9007199254740991}}),
 GroupCreateReceipt:{allOf:[ref('Group'),object({request_id:id},['request_id'])]},
 GroupRequestLookup:{oneOf:[object({request_id:id,found:{const:false}},undefined,false),object({request_id:id,found:{const:true},group:ref('GroupCreateReceipt')},undefined,false)]},
 GroupRequestPage:object({items:{type:'array',maxItems:50,items:object({request_id:id,group_id:id,group_name:nullable(bounded(240)),created_at:date},undefined,false)},total:auditInteger,page:pageNumber,page_size:{type:'integer',minimum:1,maximum:50}},undefined,false),
 Token:object({id,name:str,expires_at:date,uses:integer,max_uses:nullable(integer),name_prefix:nullable(str),revoked:bool,created_at:date}),
 TokenCreated:object({token:str,record:ref('Token')},undefined,false),
 EnrollmentTokenRecord:object({id,name:{type:'string',minLength:1,maxLength:120},expires_at:date,uses:{type:'integer',minimum:0,maximum:9007199254740991},max_uses:nullable({type:'integer',minimum:1,maximum:100000}),name_prefix:nullable({type:'string',maxLength:80,pattern:'^[a-z0-9-]*$'}),revoked:bool,created_at:date},undefined,false),
 TokenCreateReceipt:object({request_id:id,request_correlation:{const:true},token:{type:'string',minLength:1,maxLength:512},record:{allOf:[ref('EnrollmentTokenRecord'),{properties:{uses:{const:0},revoked:{const:false}}}]}},undefined,false),
 TokenRequestStatus:{oneOf:[object({request_id:id,request_correlation:{const:true},found:{const:false}},undefined,false),object({request_id:id,request_correlation:{const:true},found:{const:true},state:{const:'created'},record:ref('EnrollmentTokenRecord')},undefined,false),object({request_id:id,request_correlation:{const:true},found:{const:true},state:{const:'cancelled'},record:{oneOf:[{type:'null'},{allOf:[ref('EnrollmentTokenRecord'),{properties:{revoked:{const:true}}}]}]}},undefined,false)],description:'Actor-scoped exact creation identity. Lookup never reveals a secret. A negative read is not cancellation; cancellation fences late creation and revokes the mapped token atomically.'},
 EnrollmentTokenCreateResult:{oneOf:[ref('TokenCreated'),ref('TokenCreateReceipt'),{allOf:[ref('TokenRequestStatus'),{properties:{found:{const:true}}}]}]},
 DeviceRevocationStatus:object({device_id:id,revocation_status:{const:true},revoked:bool},undefined,false),
 DeviceRevocationReceipt:object({device_id:id,revocation_status:{const:true},revoked:{const:true},ok:{const:true}},undefined,false),
 DeviceRecoveryTokenRecord:object({id,name:{type:'string',minLength:1,maxLength:120},expires_at:date,uses:{type:'integer',minimum:0,maximum:1},max_uses:{const:1},name_prefix:{type:'null'},revoked:bool,created_at:date,recovery_device_id:id,recovery_name:{type:'string',minLength:1,maxLength:100}},undefined,false),
 DeviceRecoveryTokenReceipt:object({request_id:id,request_correlation:{const:true},device_id:id,token:{type:'string',minLength:1,maxLength:512},record:{allOf:[ref('DeviceRecoveryTokenRecord'),{properties:{uses:{const:0},revoked:{const:false}}}]}},undefined,false),
 DeviceRecoveryRequestStatus:{oneOf:[object({request_id:id,request_correlation:{const:true},device_id:id,found:{const:false}},undefined,false),object({request_id:id,request_correlation:{const:true},device_id:id,found:{const:true},state:{const:'created'},record:ref('DeviceRecoveryTokenRecord')},undefined,false),object({request_id:id,request_correlation:{const:true},device_id:id,found:{const:true},state:{const:'cancelled'},record:{oneOf:[{type:'null'},{allOf:[ref('DeviceRecoveryTokenRecord'),{properties:{revoked:{const:true}}}]}]}},undefined,false)],description:'Current administrator own recovery request bound to its original device UUID. Record recovery_device_id must equal envelope device_id, and recovery_name must equal the reviewed expected_name. No secret replay. A negative read does not fence late issuance. Cancellation revokes only the mapped token; completed replacement identities remain unchanged.'},
 DeviceRecoveryCreateResult:{oneOf:[ref('TokenCreated'),ref('DeviceRecoveryTokenReceipt'),{allOf:[ref('DeviceRecoveryRequestStatus'),{properties:{found:{const:true}}}]}]},
 DeviceRecoveryRequest:{oneOf:[object({},[],false),object({request_id:id,expected_name:{type:'string',minLength:1,maxLength:100}},undefined,false)],description:'Empty legacy request or strict correlated request. The expected name must exactly match the original source device on first issuance. Same actor/request key cannot be rebound to another device or reviewed name.'},
 Release:object({name:str,os:str,arch:str,version:str,sha256:hash,size:integer,url:str,signed:bool}),
 Validation:object({valid:bool,errors:array(str),warnings:array(str),vector_validated:bool,vector_version:str,deferred:bool,deferred_reasons:array(str)},['valid','errors','warnings']),
 PipelineTestResult:object({valid:bool,tests_run:bool,errors:array(str),warnings:array(str),output:str,deferred:bool,deferred_reasons:array(str),vector_version:str},['valid','tests_run','errors','vector_version']),
 EnrollmentRequest:object({configuration_mode:configurationMode,protocol_version:{const:1},request_id:{type:'string',minLength:1,maxLength:128},token:{type:'string',minLength:1,maxLength:512},name:{type:'string',minLength:1,maxLength:100},csr_pem:{type:'string',minLength:1,maxLength:16384},os:str,arch:str,agent_version:str,vector_version:str},['protocol_version','request_id','token','name','csr_pem','os','arch','agent_version','vector_version']),
 Credential:object({device_id:id,certificate_pem:str,ca_pem:str,signing_public_key:{type:'string',contentEncoding:'base64'},certificate_expires_at:date}),
 HeartbeatRequest:object({configuration_mode:configurationMode,protocol_version:{const:1},request_id:str,nonce:{type:'string',contentEncoding:'base64',description:'Exactly 32 unpredictable decoded bytes'},boot_id:str,agent_version:str,vector_version:str,reported_generation:integer,policy_generation:integer,actual_sha256:nullable(str),applied_template_sha256:nullable(hash),secret_revision:integer,apply_state:{enum:['unmanaged','desired','downloaded','validated','written','reload_requested','verified_applied','verification_unknown','failed','rolled_back','paused']},local_paused:bool,remote_pause_acknowledged:bool,telemetry:nullable(ref('Telemetry')),error:nullable(object({code:str,stage:str,message:str}))},['protocol_version','request_id','nonce','boot_id','agent_version','vector_version','reported_generation','policy_generation','actual_sha256','apply_state','local_paused','remote_pause_acknowledged']),
 DesiredArtifact:object({version_id:id,sha256:{...hash,description:'Digest of exact target-specific rendered artifact bytes, not necessarily the published base-version digest.'},size:{type:'integer',minimum:1,maximum:1048576},artifact_path:{type:'string',pattern:'^/agent/v1/artifacts/[a-f0-9]{64}$'},vector_version:str}),
 Manifest:object({protocol_version:{const:1},device_id:id,nonce:str,issued_at:date,expires_at:date,generation:integer,policy_generation:integer,policy:ref('AgentPolicy'),desired:nullable(ref('DesiredArtifact'))}),
 SignedManifest:object({payload:{type:'string',contentEncoding:'base64',description:'Exact UTF-8 JSON Manifest bytes, decoded before signature verification'},signature:{type:'string',contentEncoding:'base64',description:'Ed25519 signature over exact decoded payload'}}),
};
schemas.Deployment.properties.rollback_idempotency={const:true,description:'This server supports durable actor-scoped rollback request identities.'};
schemas.Deployment.properties.rollback_review={const:true,description:'This server supports read-only rollback scope review and a transactionally checked review token.'};
schemas.Deployment.properties.request_correlation={const:true,description:'Keyed create/rollback receipts and exact request lookup echo durable request, operation and source identity.'};
schemas.Preview.properties.request_correlation=schemas.Deployment.properties.request_correlation;
schemas.Device.properties.retry_preconditions={const:true,description:'Retry requires the reviewed desired version and generation plus current retryable state and enabled sync.'};
schemas.Device.properties.desired_sha256={...nullable(hash),description:'Exact rendered artifact digest for the currently released device generation. Version identity, delivered artifact bytes, and actual managed-file digest are distinct.'};
schemas.Device.properties.configuration_attempt=ref('ConfigurationAttempt');
schemas.Device.properties.reported_apply_state={type:'string',description:'Agent-reported workload state, separate from progress of the current desired assignment.'};
schemas.HeartbeatRequest.properties.configuration_attempt=ref('ConfigurationAttempt');
for(const field of ['generation','policy_generation']) schemas.Manifest.properties[field]={...integer,maximum:9007199254740991};
for(const field of ['reported_generation','policy_generation','secret_revision']) schemas.HeartbeatRequest.properties[field]={...integer,maximum:9007199254740991};
schemas.DeploymentSummary.properties.rollback_idempotency=schemas.Deployment.properties.rollback_idempotency;
schemas.DeploymentSummary.properties.rollback_review=schemas.Deployment.properties.rollback_review;
schemas.DeploymentSummary.properties.request_correlation=schemas.Deployment.properties.request_correlation;
const gateCount={type:'integer',minimum:0,maximum:9007199254740991};
const gateReason={enum:['superseded','stale','paused','unverified','unavailable']};
schemas.CanaryGate=object({state:{enum:['waiting','observing','paused']},released_count:gateCount,verified_count:gateCount,pending_count:gateCount,reasons:object(Object.fromEntries(gateReason.enum.map(reason=>[reason,gateCount])),undefined,false),observation_started_at:nullable(date),observation_seconds:{type:'integer',minimum:0,maximum:86400},evaluated_at:date},undefined,false);
schemas.CanaryGate.description='Read-only current canary evidence, separate from historical progress. Each released target contributes exactly once to verified_count or one reason. Only observing has a nonnull observation start and requires every released target to be currently verified. Counts and evaluation share a read snapshot; no countdown or future release promise.';
schemas.CanaryGate.allOf=[{if:{properties:{state:{const:'observing'}}},then:{properties:{observation_started_at:date,released_count:{...gateCount,minimum:1}}},else:{properties:{observation_started_at:{type:'null'}}}}];
schemas.DeploymentSummary.properties.canary_gate={...ref('CanaryGate'),description:'Present only on the single-deployment summary for active/paused canaries; omitted from paged history and other rollout states. Absence does not establish readiness.'};
schemas.DeploymentTargetSummary.properties.gate_reason={...nullable(gateReason),description:'Current gate blocker for this target of an active/paused canary. Null also covers pending or no-longer-targeted rows and must not be interpreted as verified. Omitted outside this context or by older servers.'};
schemas.DeploymentHistoryPage.properties.request_history={const:true,description:'Supporting servers offer authenticated actor-scoped committed deployment request discovery.'};
schemas.RollbackRequest=object({request_id:id,review_token:hash},[],false);
schemas.RollbackPreview=object({source_deployment_id:id,source_version_id:id,source_status:{type:'string',minLength:1,maxLength:64},source_action:{enum:['cancel','unassign']},previous_version_id:nullable(id),previous_version_number:nullable({type:'integer',minimum:1,maximum:9007199254740991}),previous_configuration_id:nullable(id),previous_configuration_name:nullable(bounded(240)),priority:{type:'integer',minimum:-1000000,maximum:1000000},eligible_devices:{type:'array',maxItems:10000,items:object({device_id:id,device_name:nullable(bounded(240)),artifact_sha256:hash},undefined,false)},excluded_devices:{type:'array',maxItems:10000,items:object({device_id:id,device_name:nullable(bounded(240)),reason:{enum:['revoked','removed','not_released','missing']}},undefined,false)},blockers:{type:'array',maxItems:10000,items:object({code:{type:'string',minLength:1,maxLength:64},reason:{type:'string',minLength:1,maxLength:1000}},undefined,false)},review_token:hash,ready:bool},undefined,false);
schemas.RemovalState=object({assignment_id:nullable(id),assignment_name:nullable(bounded(120)),version_id:nullable(id),configuration_name:nullable(bounded(240)),version_number:nullable(pageNumber),generation:auditInteger,policy:nullable(ref('AgentPolicy'))},undefined,false);
schemas.AssignmentRemovalPreview=object({removal_review:{const:true},source_deployment_id:id,source_status:{type:'string',minLength:1,maxLength:64},resource:{enum:['configuration','policy']},ready:bool,review_token:hash,blockers:{type:'array',maxItems:10000,items:object({code:{type:'string',minLength:1,maxLength:64},reason:{type:'string',minLength:1,maxLength:1000}},undefined,false)},devices:{type:'array',maxItems:10000,items:object({device_id:id,device_name:nullable(bounded(240)),effect:{enum:['fallback','unmanaged','default_policy','retained_pending','unchanged','revoked','missing','not_targeted']},before:nullable(ref('RemovalState')),after:nullable(ref('RemovalState')),pending_assignment_id:nullable(id),pending_assignment_name:nullable(bounded(120))},undefined,false)}},undefined,false);
schemas.AssignmentRemovalPreview.description='Read-only removal simulation. Every device identity is distinct, ready is true exactly when blockers is empty, and an empty ready scope is allowed. Fingerprint binds the actor, source and meaningful current/projected delivery state, not display metadata or telemetry. Configuration removal can retain local workload; policy removal can restore defaults. Pending candidates are not delivered assignments.';
const removalStates=properties=>({before:{properties},after:{properties}});
const configurationRemovalStates=removalStates({policy:{type:'null'}});
const policyRemovalStates=removalStates({version_id:{type:'null'},configuration_name:{type:'null'},version_number:{type:'null'},policy:ref('AgentPolicy')});
schemas.AssignmentRemovalPreview.allOf=[
 {if:{properties:{ready:{const:true}}},then:{properties:{blockers:{maxItems:0}}},else:{properties:{blockers:{minItems:1}}}},
 {if:{properties:{resource:{const:'configuration'}}},then:{properties:{devices:{items:{properties:{...configurationRemovalStates,effect:{not:{const:'default_policy'}}}}}}},else:{properties:{devices:{items:{properties:{...policyRemovalStates,effect:{not:{const:'unmanaged'}}}}}}}}
];
schemas.AssignmentRemovalPreview.properties.devices.items.allOf=[
 {if:{properties:{effect:{const:'missing'}}},then:{properties:{before:{type:'null'},after:{type:'null'}}},else:{properties:{before:{type:'object'},after:{type:'object'}}}},
 {if:{properties:{effect:{const:'fallback'}}},then:{properties:{after:{properties:{assignment_id:id}}}}},
 {if:{properties:{effect:{const:'unmanaged'}}},then:{properties:{after:{properties:{assignment_id:{type:'null'},version_id:{type:'null'}}}}}},
 {if:{properties:{effect:{const:'default_policy'}}},then:{properties:{after:{properties:{assignment_id:{type:'null'},policy:ref('AgentPolicy')}}}}},
 {if:{properties:{effect:{const:'retained_pending'}}},then:{properties:{pending_assignment_id:id}}}
];
schemas.AssignmentRemovalRequest=object({review_token:hash},undefined,false);
schemas.ScheduledRefreshDevice=object({id,name:nullable(bounded(240)),status:{type:'string',minLength:1,maxLength:64}},undefined,false);
schemas.ScheduledRefreshPreview=object({refresh_review:{const:true},source_deployment_id:id,source_status:deploymentStatus,resource:{enum:['configuration','policy']},scheduled_at:date,ready:bool,review_token:hash,saved_devices:{type:'array',maxItems:10000,items:ref('ScheduledRefreshDevice')},devices:{type:'array',maxItems:10000,items:ref('ScheduledRefreshDevice')},warnings:{type:'array',maxItems:10000,items:{type:'string',minLength:1,maxLength:1000}},blockers:{type:'array',maxItems:10000,items:object({code:{type:'string',minLength:1,maxLength:64},reason:{type:'string',minLength:1,maxLength:1000}},undefined,false)}},undefined,false);
schemas.ScheduledRefreshPreview.allOf=[{if:{properties:{ready:{const:true}}},then:{properties:{source_status:{const:'scheduled'},blockers:{maxItems:0},devices:{minItems:1}}},else:{properties:{blockers:{minItems:1}}}},{if:{properties:{source_status:{not:{const:'scheduled'}}}},then:{properties:{devices:{maxItems:0}}}}];
schemas.ScheduledRefreshPreview.description='Read-only comparison of the saved scheduled snapshot and current selector resolution. Device identities are distinct within each list; the combined union is bounded to10000. Ready is true exactly when blockers is empty; an empty proposed selection is blocked. New UUIDs without complete typed bindings produce VARIABLE_BINDING_REQUIRED; the actor-bound token covers frozen bindings, source settings, saved/proposed membership and an internal monotonic revision so delayed requests cannot overwrite a newer review, including an ABA change. Matching no-op does not mutate or audit. Names and connection status are display metadata. Current saved selection does not attribute an earlier request or establish activation.';
schemas.ScheduledRefreshRequest=object({review_token:hash,expected_device_ids:{type:'array',minItems:1,maxItems:10000,uniqueItems:true,items:id}},undefined,false);
schemas.RollbackPreview.description='Complete metadata-only historical scope, bounded to 10000 distinct device UUIDs across both lists. Ready requires at least one eligible device, a common previous version and no blockers. Each eligible target exposes the exact prior artifact digest, never its bytes or binding values. Names are display-only. The token binds source, exact eligible/excluded identities and reasons, prior version, prior target artifact digests and generations, admission and current assignment state.';
schemas.DeviceRetryRequest=object({expected_version_id:id,expected_generation:{type:'integer',minimum:1,maximum:9007199254740991}},undefined,false);
const paths={};
const response=schema=>({'200':{description:'Success',content:{'application/json':{schema}}},'400':{description:'Invalid input',content:{'application/json':{schema:ref('Error')}}},'401':{description:'Authentication required',content:{'application/json':{schema:ref('Error')}}},'403':{description:'Forbidden',content:{'application/json':{schema:ref('Error')}}},'409':{description:'Conflict or stale revision',content:{'application/json':{schema:ref('Error')}}},'429':{description:'Rate limit'}});
function route(path,method,summary,out={},body,publicRoute=false,device=false){paths[path]??={};paths[path][method]={summary,operationId:method+'_'+path.replace(/[^a-z0-9]/gi,'_'),security:publicRoute?[]:device?[{deviceMTLS:[]}]:[{sessionCookie:[]}],parameters:[...Array.from(path.matchAll(/\{(\w+)\}/g),m=>({name:m[1],in:'path',required:true,schema:str})),...(!device&&!publicRoute&&method!=='get'?[{name:'X-CSRF-Token',in:'header',required:true,schema:str}]:[])],...(body?{requestBody:{required:true,content:{'application/json':{schema:body}}}}:{}),responses:response(out)};}
route('/api/v1/status','get','Public initialization status',ref('Status'),null,true);
route('/api/v1/bootstrap','post','Transactionally initialize the first administrator',ref('Session'),object({bootstrap_secret:str,email:str,name:str,password:{type:'string',minLength:12}}),true);
route('/api/v1/login','post','Check credentials; return a session or a five-minute MFA challenge without a session',ref('LoginResult'),object({email:str,password:str,totp_code:str,recovery_code:str},['email','password']),true);
route('/api/v1/login/mfa','post','Complete a single-use login challenge with an authenticator or recovery code',ref('Session'),{...object({challenge_token:{type:'string',pattern:'^[a-f0-9]{64}$'},totp_code:str,recovery_code:str},['challenge_token'],false),oneOf:[{required:['totp_code'],not:{required:['recovery_code']}},{required:['recovery_code'],not:{required:['totp_code']}}]},true);
route('/api/v1/session','get','Current session and CSRF token',ref('Session'));
route('/api/v1/logout','post','Revoke current session');
for(const [plural,schema] of [['devices','Device'],['configurations','Configuration'],['deployments','Deployment'],['groups','Group'],['tokens','Token'],['releases','Release'],['users','User']])route(`/api/v1/${plural}`,'get',`List ${plural}`,array(ref(schema)));
for(const [plural,schema] of [['devices','Device'],['configurations','Configuration'],['deployments','Deployment'],['versions','Version']])route(`/api/v1/${plural}/{id}`,'get',`Read ${schema}`,ref(schema));
for(const collection of ['overview','issues','audit','policies','settings'])route(`/api/v1/${collection}`,'get',`Read ${collection}`,collection==='overview'?ref('Overview'):collection==='issues'?array(ref('Issue')):{});
route('/api/v1/audit/history','get','Read bounded audit metadata in persisted timestamp/sequence order; no raw event extensions or details',ref('AuditHistoryPage'));
paths['/api/v1/audit/history'].get.parameters.push(...Object.entries(auditFilters).map(([name,schema])=>({name,in:'query',schema,description:name==='target_id'?'Exact stored target or stable typed target identity; no current group membership inference.':name==='device_id'?'Exact direct actor/target, stored device UUID, or recognized persisted release/recovery UUID pair.':name==='from'||name==='to'?'Inclusive RFC3339 UTC timestamp, at most millisecond precision.':name==='search'?'Trimmed literal metadata substring; ASCII case-insensitive, reasons/private extensions excluded.':undefined})),{name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
paths['/api/v1/audit/history'].get.parameters.push({name:'sort',in:'query',schema:{enum:['action','actor','outcome','created_at'],default:'created_at'},description:'Global metadata order before pagination. Time uses durable sequence in the same direction to break ties; other sorts use durable sequence descending. Export order is unchanged.'},{name:'direction',in:'query',schema:{enum:['asc','desc'],default:'desc'}});
route('/api/v1/audit/{id}','get','Read safe action-specific audit detail; current exact-ID names are not historical name snapshots',ref('AuditDetail'));
route('/api/v1/audit/exports','get','List at most two prepared exports belonging to this user and originating browser session',{type:'array',maxItems:2,items:ref('AuditExport')});
route('/api/v1/audit/exports','post','Prepare a complete private JSONL snapshot before returning download metadata; requires CSRF',ref('AuditExport'),ref('AuditExportFilters'));
for(const code of ['408','413','500'])paths['/api/v1/audit/exports'].post.responses[code]={description:code==='408'?'Preparation deadline exceeded':code==='413'?'Explicit row or byte limit exceeded; narrow filters':'Preparation failed; no ready file',content:{'application/json':{schema:ref('Error')}}};
route('/api/v1/audit/exports/{id}','delete','Discard own session-bound prepared export; active downloads retain their file and quota until closed',object({ok:bool},undefined,false));
route('/api/v1/audit/exports/{id}/download','get','Download the completed snapshot with exact Content-Length; owner and originating session are required and rechecked during transfer');
paths['/api/v1/audit/exports/{id}/download'].get.responses['200']={description:'Prepared UTF-8 JSONL metadata, audit events and count/hash completion trailer. A ready file is not proof the browser saved it.',headers:{'Content-Length':{required:true,schema:integer},'Content-Disposition':{required:true,schema:str},'Cache-Control':{required:true,schema:{const:'no-store'}}},content:{'application/x-ndjson':{schema:{type:'string',format:'binary'}}}};
route('/api/v1/issues/history','get','Read a bounded issue page with exact-identity device metadata; resolved takes precedence over acknowledgement',ref('IssueHistoryPage'));
paths['/api/v1/issues/history'].get.parameters.push({name:'search',in:'query',schema:{type:'string',maxLength:200,default:''},description:'Trimmed literal substring of device UUID/name, code, stage or sanitized message. ASCII case-insensitive. Reasons and private diagnostics are not searched.'},{name:'state',in:'query',schema:{enum:['open','acknowledged','resolved','all'],default:'open'}},{name:'device_id',in:'query',schema:id,description:'Exact original device UUID; replacement names are not followed.'},{name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
paths['/api/v1/issues/history'].get.parameters.push({name:'sort',in:'query',schema:{enum:['code','device','last_seen','count','disposition'],default:'last_seen'},description:'Global order before pagination using bounded projected fields, original issue ID ascending as tie-break and unavailable dates last.'},{name:'direction',in:'query',schema:{enum:['asc','desc'],default:'desc'}});
route('/api/v1/issues/{id}','get','Read one sanitized issue and its current disposition',ref('Issue'));
for(const action of ['acknowledge','reopen'])route(`/api/v1/issues/{id}/${action}`,'post',`Operator ${action}s an unresolved issue on an exactly identified revoked device under revision CAS; audit and state change are atomic; does not change verified resolution or device configuration`,ref('Issue'),object({revision:pageNumber,reason:{type:'string',minLength:1,maxLength:1000,description:'Trimmed nonempty reason, no NUL; stored in the audit log.'}},undefined,false));
for(const path of ['/api/v1/issues/{id}','/api/v1/issues/{id}/acknowledge','/api/v1/issues/{id}/reopen'])for(const operation of Object.values(paths[path]))operation.parameters.find(p=>p.name==='id'&&p.in==='path').schema=hash;
route('/api/v1/configurations/library','get','Read an authenticated bounded pipeline metadata page; no configuration, graph or artifact bodies',ref('ConfigurationLibraryPage'));
paths['/api/v1/configurations/library'].get.parameters.push({name:'search',in:'query',schema:{type:'string',maxLength:200,default:''},description:'Trimmed literal substring of name or description. ASCII case-insensitive; non-ASCII is literal. At most 200 Unicode scalar characters. SQL wildcard characters are literal.'},{name:'state',in:'query',schema:{enum:['active','archived','all'],default:'active'}},{name:'sort',in:'query',schema:{enum:['updated','name'],default:'updated'},description:'Global sort before pagination. Defaults: updated descending then name/ID ascending; name ascending then ID. Explicit direction overrides primary order; unavailable values last.'},{name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
route('/api/v1/configurations','post','Create canonical configuration and first immutable draft revision. Optional actor-scoped request_id returns PipelineCreateReceipt; exact retries return the current original result without another creation or audit.',ref('Configuration'),object({name:{type:'string',minLength:1,maxLength:120,description:'At most 120 UTF-8 bytes; NUL is rejected. The dashboard also trims surrounding whitespace.'},description:{type:'string',maxLength:2000,description:'At most 2000 UTF-8 bytes.'},config,graph,variables:variableDeclarations,request_id:id},['name','config','graph']));
route('/api/v1/configurations/requests/{request_id}','get','Editor or administrator reads their own durable create/duplicate result. A matching key echo confirms support; found:false may still be in flight.',ref('PipelineRequestLookup'));
route('/api/v1/configurations/requests','get','Read a bounded page of current-account committed pipeline creation and duplication metadata, including other tabs/devices. No configuration, graph or original payload.',ref('PipelineRequestPage'));
paths['/api/v1/configurations/requests'].get.parameters.push({name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
route('/api/v1/configurations/{id}/draft','put','Save draft with optimistic concurrency; omitted variables preserve declarations, explicit empty array removes them',ref('Configuration'),object({revision:integer,config,graph,variables:variableDeclarations,message:str,name:{type:'string',minLength:1,maxLength:120},description:{type:'string',maxLength:2000}},['revision','config','graph']));
route('/api/v1/configurations/{id}/revisions','get','Read full immutable draft revisions in descending revision order; use history for bounded metadata',array(ref('Revision')));
route('/api/v1/configurations/{id}/versions','get','Read immutable published versions',array(ref('Version')));
paths['/api/v1/configurations/library'].get.parameters.push({name:'direction',in:'query',schema:{enum:['asc','desc']},description:'Optional primary sort direction. Omission preserves updated descending or name ascending.'});
route('/api/v1/configurations/{id}/history','get','Read a bounded metadata page without graph, config, artifact or validation bodies',ref('HistoryPage'));
paths['/api/v1/configurations/{id}/history'].get.parameters.push({name:'kind',in:'query',schema:{enum:['revisions','versions'],default:'revisions'}},{name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
route('/api/v1/configurations/{id}/revisions/{revision_id}','get','Read one full immutable draft snapshot, requiring matching parent pipeline',ref('Revision'));
route('/api/v1/configurations/{id}/duplicate','post','Editor duplicates the saved draft under CAS; archived sources allowed. Optional request_id shares the create namespace and returns PipelineCreateReceipt. Exact replay recovers the current original copy before reading the source or comparing revisions.',ref('Configuration'),object({revision:pageNumber,name:{type:'string',minLength:1,maxLength:120,description:'At most 120 UTF-8 bytes.'},description:{type:'string',maxLength:2000,description:'At most 2000 UTF-8 bytes. Omission copies the source description and differs from an explicitly empty string for request binding.'},request_id:id},['revision','name']));
for(const action of ['archive','unarchive'])route(`/api/v1/configurations/{id}/${action}`,'post',`Editor ${action}s draft library state under CAS; existing versions and deployments remain usable`,ref('Configuration'),object({revision:revisionNumber}));
route('/api/v1/configurations/{id}/restore','post','Editor restores same-pipeline snapshot content as a new draft revision, preserving current name and description',ref('Configuration'),{...object({revision:revisionNumber,revision_id:id,version_id:id,message:{type:'string',maxLength:2000}},['revision']),oneOf:[{required:['revision_id'],not:{required:['version_id']}},{required:['version_id'],not:{required:['revision_id']}}]});
route('/api/v1/configurations/{id}/validate','post','Validate structure and configured isolated worker',ref('Validation'),object({config}));
route('/api/v1/configurations/{id}/publish','post','Publish immutable artifact without deploying. An optional actor-scoped request_id returns a PublishReceipt; identical retries recover the original immutable version before checking later draft or validation state.',ref('Version'),object({revision:pageNumber,message:{...str,maxLength:2000,description:'At most 2000 UTF-8 bytes. Optional for keyed calls; omission differs from an explicitly empty string for request binding.'},request_id:id},['revision']));
route('/api/v1/configurations/publish-requests/{request_id}','get','Operator or administrator reads their own durable publish result. A matching request_id echo confirms support; found:false can still be in flight.',ref('PublishRequestLookup'));
route('/api/v1/configurations/publish-requests','get','Read current account committed publication metadata for one exact pipeline, including other tabs/devices; no configuration, artifact, message or original payload.',ref('PublishRequestPage'));
paths['/api/v1/configurations/publish-requests'].get.parameters.push({name:'configuration_id',in:'query',required:true,schema:id},{name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
route('/api/v1/deployments/history','get','Read a bounded deployment metadata page, with persisted target counts and current UUID-bound pipeline names; no configuration, artifact, selector or target arrays',ref('DeploymentHistoryPage'));
paths['/api/v1/deployments/history'].get.parameters.push({name:'search',in:'query',schema:{type:'string',maxLength:200,default:''},description:'Literal substring of deployment/pipeline name, status, version label or policy subtitle. At most 200 Unicode scalar characters; ASCII case-insensitive.'},{name:'status',in:'query',schema:{enum:['all',...deploymentStatus.enum],default:'all'}},{name:'scheduled',in:'query',schema:bool,description:'Omit for all deployments. True includes records with a scheduled time, including completed/cancelled/missed schedules; false includes only unscheduled records.'},{name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
paths['/api/v1/deployments/history'].get.parameters.push({name:'sort',in:'query',schema:{enum:['name','status','verified','created_at','scheduled_at'],default:'created_at'},description:'Global order before pagination. Name/status use displayed labels; verified uses the persisted verified_applied count, then total target count. UUID ascending breaks ties; unavailable values are last.'},{name:'direction',in:'query',schema:{enum:['asc','desc'],default:'desc'}});
route('/api/v1/deployments/{id}/summary','get','Read one deployment metadata summary without selector or targets; only verified_applied rows count as verified',ref('DeploymentSummary'));
route('/api/v1/deployments/{id}/targets','get','Read a bounded page of persisted targets belonging to this deployment; names remain bound to the original UUID',ref('DeploymentTargetPage'));
paths['/api/v1/deployments/{id}/targets'].get.parameters.push({name:'search',in:'query',schema:{type:'string',maxLength:200,default:''},description:'Literal device name/UUID substring, not error text.'},{name:'state',in:'query',schema:{type:'string',pattern:'^[A-Za-z0-9_]{1,64}$',default:'all'},description:'All or one exact persisted state; new states remain readable.'},{name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
paths['/api/v1/deployments/{id}/targets'].get.parameters.push({name:'sort',in:'query',schema:{enum:['device_name','state','generation'],default:'device_name'},description:'Global order before pagination. Device name falls back to the original UUID; state uses the visible progress label. Original UUID ascending breaks ties; unavailable values are last.'},{name:'direction',in:'query',schema:{enum:['asc','desc'],default:'asc'}});
route('/api/v1/deployments/preview','post','Preview effective targets and transactional priority conflicts',ref('Preview'),ref('DeploymentRequest'));
route('/api/v1/deployments','post','Create immediate or scheduled deployment. Keyed requests return DeploymentReceipt with durable request correlation; unkeyed legacy requests return Deployment.',ref('Deployment'),ref('DeploymentRequest'));
route('/api/v1/deployments/requests/{request_id}','get','Operator or administrator confirms their own durable create or rollback result; echoed outer and inner request/operation/source identities must match; not found may still be in flight',ref('DeploymentRequestStatus'));
route('/api/v1/deployments/requests','get','Operator or administrator browses their own committed create and rollback results; absent requests may still be in flight and rows cannot reconstruct a retry',ref('DeploymentRequestPage'));
paths['/api/v1/deployments/requests'].get.parameters.push({name:'operation',in:'query',schema:{enum:['all','create','rollback'],default:'all'}},{name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
for(const action of ['pause','resume','cancel'])route(`/api/v1/deployments/{id}/${action}`,'post',`${action} deployment`,ref('Deployment'));
route('/api/v1/deployments/{id}/unassign','post','Remove an assignment only if its reviewed scope and projected effects still match; 409 ASSIGNMENT_REMOVAL_REVIEW_CHANGED requires explicit fresh review. Missing review token is rejected.',ref('Deployment'),ref('AssignmentRemovalRequest'));
paths['/api/v1/deployments/{id}/resume'].post.summary='Resume a paused deployment after rechecking active-canary admission; 409 ACTIVE_CANARY_OVERLAP preserves all state; success returns the exact source deployment';
route('/api/v1/deployments/{id}/rollback-preview','get','Operator or administrator reviews the exact rollback scope without mutation; ready does not reserve assignments',ref('RollbackPreview'));
route('/api/v1/deployments/{id}/rollback','post','Create a replacement deployment; optional review token rejects changed scope with ROLLBACK_REVIEW_CHANGED. Keyed requests return DeploymentReceipt and replay the current original result with exact request/operation/source identity.',ref('Deployment'),ref('RollbackRequest'));
route('/api/v1/deployments/{id}/refresh-preview','post','Review saved and proposed scheduled membership without changing targets, desired state or audit history; Operator/Admin and CSRF required',ref('ScheduledRefreshPreview'),object({},undefined,false));
route('/api/v1/deployments/{id}/unassign-preview','post','Operator or administrator reviews the current exact assignment removal effects without changing assignments, generations or audit history; CSRF required',ref('AssignmentRemovalPreview'));
route('/api/v1/deployments/{id}/refresh','post','Replace the scheduled snapshot only when the actor-bound review token and complete reviewed IDs remain current; changed review requires a separate new confirmation',ref('Deployment'),ref('ScheduledRefreshRequest'));
const groupBody=object({name:str,description:str,device_ids:array(id)});
route('/api/v1/groups','post','Create operator-controlled group; optional actor-scoped request_id returns a GroupCreateReceipt and replays the same current group without another mutation or audit',ref('Group'),object({...groupBody.properties,request_id:id},Object.keys(groupBody.properties)));
route('/api/v1/groups/requests/{request_id}','get','Operator or administrator reads their own durable group-create result; not found may still be in flight. request_id echo confirms keyed creation support.',ref('GroupRequestLookup'));
route('/api/v1/groups/requests','get','Read a bounded metadata page of the current account\'s committed group-create requests, including requests from other tabs or devices; no original payload or membership arrays',ref('GroupRequestPage'));
paths['/api/v1/groups/requests'].get.parameters.push({name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
route('/api/v1/groups/{id}','get','Read group with current revision (legacy records start at zero)',ref('Group'));route('/api/v1/groups/{id}','put','Update reviewed metadata and membership under revision CAS; stale revisions return 409 STALE_REVISION; new persistent members overlapping another active canary return 409 ACTIVE_CANARY_OVERLAP; rejected edits leave assignments unchanged',ref('Group'),object({...groupBody.properties,revision:{type:'integer',minimum:0,maximum:9007199254740991}}));
route('/api/v1/policies','post','Save complete agent settings; optional actor-scoped request_id recovers the same original template without another save or audit',ref('SavedPolicy'),object({name:{type:'string',minLength:1,maxLength:120},policy:ref('AgentPolicy'),request_id:id},['name','policy']));
paths['/api/v1/policies'].post.responses['200'].content['application/json'].schema={oneOf:[ref('SavedPolicy'),ref('PolicyCreateReceipt')]};
route('/api/v1/policies/requests','get','Read bounded current-account committed settings-save metadata, including other tabs/devices; no original retry payload',ref('PolicyRequestPage'));
paths['/api/v1/policies/requests'].get.parameters.push({name:'page',in:'query',schema:{...pageNumber,default:1}},{name:'page_size',in:'query',schema:{type:'integer',minimum:1,maximum:50,default:12}});
route('/api/v1/policies/requests/{request_id}','get','Look up the exact current-account settings-save request; create_idempotency proves recovery support and found:false is not cancellation',ref('PolicyRequestLookup'));
route('/api/v1/tokens','post','Create scoped enrollment token; optional actor-scoped request_id prevents duplicate creation and supports cancellation without retaining its one-time secret',ref('EnrollmentTokenCreateResult'),object({name:{type:'string',minLength:1,maxLength:120},expires_hours:{type:'integer',minimum:1,maximum:720},max_uses:nullable({type:'integer',minimum:1,maximum:100000}),name_prefix:nullable({type:'string',maxLength:80,pattern:'^[a-z0-9-]*$'}),request_id:id},['name','expires_hours']));
route('/api/v1/tokens/requests/{request_id}','get','Look up current administrator own exact enrollment-token creation request; never returns its secret; found:false does not cancel a late request',ref('TokenRequestStatus'));
route('/api/v1/tokens/requests/{request_id}/cancel','post','Atomically close an own creation request and revoke only its mapped token if any; fence late creates; safe to repeat',ref('TokenRequestStatus'),object({}));
route('/api/v1/tokens/{id}/revoke','post','Revoke future enrollment permission');
route('/api/v1/devices/{id}/revocation','get','Read exact device identity access state; Operator/Admin; no operation attribution',ref('DeviceRevocationStatus'));
route('/api/v1/devices/{id}/revoke','post','Revoke registered identity and credentials, remove memberships and persistent targets; repeated revocation is a no-op',ref('DeviceRevocationReceipt'),object({},[],false));
for(const p of ['/api/v1/devices/{id}/revocation','/api/v1/devices/{id}/revoke'])for(const operation of Object.values(paths[p]))operation.parameters.find(parameter=>parameter.in==='path').schema=id;
route('/api/v1/devices/{id}/recover','post','Administrator authorizes one-time identity recovery; correlated requests prevent duplicate issuance without retaining the secret',ref('DeviceRecoveryCreateResult'),ref('DeviceRecoveryRequest'));
route('/api/v1/devices/{id}/recovery-requests/{request_id}','get','Read own exact device recovery authorization request; no secret replay',ref('DeviceRecoveryRequestStatus'));
route('/api/v1/devices/{id}/recovery-requests/{request_id}/cancel','post','Fence late recovery token issuance and revoke only this request token; preserve completed replacement identities',ref('DeviceRecoveryRequestStatus'),object({},[],false));
for(const routePath of ['/api/v1/devices/{id}/recover','/api/v1/devices/{id}/recovery-requests/{request_id}','/api/v1/devices/{id}/recovery-requests/{request_id}/cancel'])for(const operation of Object.values(paths[routePath]))for(const parameter of operation.parameters)if(parameter.in==='path')parameter.schema=id;
route('/api/v1/devices/{id}/telemetry','get','Last 120 chronological persisted telemetry buckets',ref('TelemetryHistory'));
route('/api/v1/devices/{id}/retry','post','Retry the reviewed desired version and generation only while the current state is retryable and sync is enabled',ref('Device'),ref('DeviceRetryRequest'));
const userCreateFields={name:{type:'string',minLength:1,maxLength:100},email:{type:'string',format:'email',maxLength:254},password:{type:'string',minLength:12,maxLength:256},role:schemas.User.properties.role};
route('/api/v1/users','post','Admin creates a local user; optional one-shot actor-scoped request_id permits secret-free status recovery and a cancellation fence, never password replay',ref('UserCreateResult'),{oneOf:[{...object({...userCreateFields,request_id:id},undefined,false)},{...object(userCreateFields),not:{required:['request_id']}}]});
route('/api/v1/users/requests/{request_id}','get','Admin reads own exact user-creation status; an absent request may still be in flight',ref('UserRequestStatus'));
route('/api/v1/users/requests/{request_id}/cancel','post','Admin atomically tombstones an absent own user-creation request so a delayed create cannot add an account; an already-created account remains intact',ref('UserRequestStatus'),object({},[],false));
for(const routePath of ['/api/v1/users/requests/{request_id}','/api/v1/users/requests/{request_id}/cancel'])for(const operation of Object.values(paths[routePath]))operation.parameters.find(parameter=>parameter.in==='path').schema=id;
const accessEditFields={name:str,role:schemas.User.properties.role,enabled:bool,revision:{type:'integer',minimum:1},current_password:str};
route('/api/v1/users/{id}','put','Admin changes local account with revision and password confirmation; optional actor-scoped one-shot request_id permits exact status recovery and a cancellation fence',ref('AccessEditResult'),{oneOf:[object({...accessEditFields,request_id:id},undefined,false),{...object(accessEditFields),not:{required:['request_id']}}]});
route('/api/v1/users/{id}/access-requests/{request_id}','get','Admin reads own exact access edit status and immutable applied User snapshot',ref('AccessEditRequestStatus'));
route('/api/v1/users/{id}/access-requests/{request_id}/cancel','post','Admin tombstones an absent access edit request; an applied edit is not rolled back',ref('AccessEditRequestStatus'),object({},[],false));
for(const routePath of ['/api/v1/users/{id}','/api/v1/users/{id}/access-requests/{request_id}','/api/v1/users/{id}/access-requests/{request_id}/cancel'])for(const operation of Object.values(paths[routePath]))for(const parameter of operation.parameters)if(parameter.in==='path')parameter.schema=id;
route('/api/v1/account/password','post','Change own password and rotate all sessions; return current fresh session',ref('Session'),object({current_password:str,new_password:{type:'string',minLength:12}}));
route('/api/v1/account/revoke-sessions','post','Revoke own other browser sessions',object({ok:bool}),object({current_password:str}));
const resetIssueFields={current_password:str,revision:{type:'integer',minimum:1}};
route('/api/v1/users/{id}/password-reset','post','Admin issues one-use 15-minute reset code; optional one-shot actor-scoped request_id permits exact secret-free status and cancellation',ref('ResetIssueResult'),{oneOf:[object({...resetIssueFields,request_id:id},undefined,false),{...object(resetIssueFields),not:{required:['request_id']}}]});
route('/api/v1/users/{id}/password-reset/requests/{request_id}','get','Admin reads own exact reset-code issuance status; no code recovery or replay',ref('ResetRequestStatus'));
route('/api/v1/users/{id}/password-reset/requests/{request_id}/cancel','post','Admin fences a delayed reset issue or revokes only the same request\'s still-current unused code',ref('ResetRequestStatus'),object({},[],false));
for(const routePath of ['/api/v1/users/{id}/password-reset','/api/v1/users/{id}/password-reset/requests/{request_id}','/api/v1/users/{id}/password-reset/requests/{request_id}/cancel'])for(const operation of Object.values(paths[routePath]))for(const parameter of operation.parameters)if(parameter.in==='path')parameter.schema=id;
route('/api/v1/password-reset','post','Consume password reset code; revoke all sessions without bypassing MFA',object({ok:bool}),object({code:str,new_password:{type:'string',minLength:12}}),true);
route('/api/v1/mfa','get','MFA status',object({enabled:bool}));route('/api/v1/mfa/setup','post','Password-gated MFA setup',object({secret:str,otpauth_url:str}),object({password:str}));route('/api/v1/mfa/confirm','post','Enable MFA; display one-use recovery codes once',object({enabled:bool,recovery_codes:array(str)}),object({code:str}));route('/api/v1/mfa/disable','post','Disable MFA and revoke other sessions',{},object({password:str,code:str,recovery_code:str},['password']));
route('/api/v1/configurations/test','post','Run Vector pipeline tests in the isolated bounded validator; device-only resources defer',ref('PipelineTestResult'),object({config}));
route('/api/v1/vrl/test','post','Execute synthetic VRL in the isolated bounded validator',object({valid:bool,output:{},errors:array(str),diagnostic:{...nullable({type:'string',maxLength:4096}),description:'Plain-text VRL compiler or runtime message for the submitted synthetic program, when the isolated runner produced one.'}},['valid','output','errors']),object({program:{type:'string',maxLength:16384},sample:{type:'object'}}));
route('/api/v1/openapi.json','get','Read the authenticated OpenAPI contract');
route('/agent/v1/enroll','post','Verified TLS enrollment with CSR possession proof',ref('Credential'),ref('EnrollmentRequest'),true,true);
route('/agent/v1/heartbeat','post','Active registered mTLS device heartbeat; signed nonce-bound desired state',ref('SignedManifest'),ref('HeartbeatRequest'),false,true);
route('/agent/v1/renew','post','Renew or rotate key with current active authentication',ref('Credential'),object({csr_pem:str}),false,true);
route('/agent/v1/artifacts/{sha256}','get','Fetch only current released device artifact',{type:'string'},null,false,true);
paths['/agent/v1/artifacts/{sha256}'].get.responses['200'].content={'application/json':{schema:{type:'string',description:'Exact UTF-8 Vector JSON artifact bytes, not a JSON string wrapper'}}};
const spec={openapi:'3.1.0',info:{title:'Vectory control plane',version:'0.1.0',description:'Single-instance self-hosted Vector configuration control plane. Agent paths use the separately configured TLS listener. Session mutations require CSRF. No request-body device UUID is trusted for authentication.'},servers:[{url:'/',description:'Same-origin dashboard API; agent endpoints served separately on verified TLS :8443'}],paths,components:{securitySchemes:{sessionCookie:{type:'apiKey',in:'cookie',name:'vectory_session'},deviceMTLS:{type:'mutualTLS'}},schemas}};
await fs.writeFile(new URL('./openapi.json',import.meta.url),JSON.stringify(spec,null,2)+'\n');
const replaceRefs=value=>JSON.parse(JSON.stringify(value).replaceAll('#/components/schemas/','#/$defs/'));
await fs.writeFile(new URL('./protocol.schema.json',import.meta.url),JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:'https://vectory.local/schemas/protocol-v1',title:'Vectory protocol v1',description:'Validate one named schema via $defs. Cryptographic, authorization and semantic checks remain mandatory.',$defs:replaceRefs(schemas)},null,2)+'\n');
console.log(`Generated ${Object.keys(paths).length} OpenAPI paths and ${Object.keys(schemas).length} shared schemas.`);
