pub mod access_requests;
pub mod accounts;
pub mod agent_release;
pub mod agent_release_keys;
pub mod agent_releases;
pub mod agent_update_rollouts;
pub mod agent_updates;
pub mod api;
pub mod assignment_removal;
pub mod audit;
pub mod audit_exports;
pub mod auth;
pub mod canary_choice;
pub mod canary_gate;
// Generated by scripts/generate-capability-table.mjs; nothing reads it yet.
#[allow(dead_code)]
mod capability_table;
pub mod configuration_attempt;
pub mod crypto;
pub mod data_plane;
pub mod db;
pub mod deployment_history;
pub mod deployment_requests;
pub mod detection;
pub mod device;
pub mod device_ca;
pub mod device_recovery_requests;
pub mod device_revocation;
pub mod device_validations;
pub mod effective_config;
pub mod enrollment_audit;
pub mod enrollment_scope;
pub mod error;
pub mod fleet;
pub mod group_requests;
pub mod groups;
pub mod http_listener;
pub mod install;
pub mod issues;
pub mod ledger;
pub mod login_challenges;
pub mod maintenance;
pub mod mfa;
pub mod notifications;
pub mod notifier;
pub mod outbound;
pub mod overview;
pub mod pipeline_library;
pub mod pipeline_requests;
pub mod pipelines;
pub mod policy_requests;
pub mod publication_requests;
pub mod publish_tests;
pub mod reset_requests;
pub mod restored_access;
pub mod rollback_review;
pub mod rollout;
pub mod schedule;
pub mod scheduled_refresh;
pub mod telemetry;
pub mod tls_reload;
pub mod token_requests;
pub mod user_requests;
pub mod validation;
pub mod validation_socket;
pub mod variables;
pub mod vector_diagnostics;
pub mod wake;
#[cfg(windows)]
mod windows_acl;

use anyhow::Context;
use sqlx::{
    SqlitePool,
    sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions, SqliteSynchronous},
};
use std::{collections::HashMap, path::PathBuf, sync::Arc, time::Duration};
use tokio::sync::Mutex;

#[derive(Clone, Default)]
pub struct Settings {
    pub data_dir: PathBuf,
    pub bootstrap_secret: String,
    pub cookie_secure: bool,
    pub dashboard_dir: PathBuf,
    pub releases_dir: PathBuf,
    pub instance_name: String,
    pub validation_url: Option<String>,
    /// Take the client address from the last X-Forwarded-For hop. Enable only
    /// when the HTTP listener is reachable solely through a trusted proxy.
    pub trust_proxy_headers: bool,
    /// How many seconds after its time a due schedule still activates
    /// (`VECTORY_SCHEDULE_LATE_START_SECONDS`); None uses the one-hour default.
    pub schedule_late_start_seconds: Option<u64>,
    /// Agent builds shipped inside the server image. Entries in the operator
    /// mirror (`releases_dir`) replace the bundled build for their platform.
    pub bundled_releases_dir: Option<PathBuf>,
    /// Public HTTPS origin of the agent listener as devices reach it. When
    /// unset, Add device derives it from the dashboard's host and `agent_port`.
    pub public_agent_url: Option<String>,
    /// Public origin of the dashboard, for device links and the startup banner.
    pub public_url: Option<String>,
    /// Refuse the unauthenticated installer and agent downloads on the agent listener.
    pub disable_public_agent_downloads: bool,
    /// Port of the agent TLS listener; None when the listener is off.
    pub agent_port: Option<u16>,
    /// The certificate chain (PEM) the agent listener presents, read at startup.
    pub agent_certificate_pem: Option<String>,
    /// How notifications reach receivers. Production leaves this default;
    /// tests supply a scripted resolver and trusted roots.
    pub outbound: outbound::Options,
    /// Agent wake-ups: how many waits may be parked and how long each is held.
    pub wake: wake::Options,
    /// The most the agent release store may hold
    /// (`VECTORY_AGENT_RELEASE_STORAGE_BYTES`); None uses the 2 GiB default.
    pub agent_release_storage_bytes: Option<u64>,
}
pub struct App {
    pub pool: SqlitePool,
    pub writer: Mutex<()>,
    pub settings: Settings,
    /// The last validated listener certificate and config. Invalid replacements
    /// never replace this snapshot or change the Add device trust information.
    pub agent_tls: std::sync::RwLock<Option<tls_reload::Snapshot>>,
    pub keys: crypto::Keys,
    pub audit_exports: Arc<audit_exports::Store>,
    pub validation_slots: tokio::sync::Semaphore,
    pub agent_request_slots: tokio::sync::Semaphore,
    pub instance_lock: std::fs::File,
    /// Request limiter partitions (see `App::limit`): sign-in, browser and
    /// account keys; unauthenticated keys outside sign-in; authenticated
    /// devices. None of them can displace another's keys.
    pub limits: std::sync::Mutex<ledger::Ledger>,
    pub public_limits: std::sync::Mutex<ledger::Ledger>,
    pub device_limits: std::sync::Mutex<ledger::Ledger>,
    /// Sign-in failure counts and recently successful clients, per account.
    pub sign_in_failures: std::sync::Mutex<ledger::Ledger>,
    /// Release file SHA-256 keyed by name and the (length, modified) pair it was computed for.
    pub release_hashes: std::sync::Mutex<HashMap<String, (u64, std::time::SystemTime, String)>>,
    /// Notification sends in flight and the notifier's schedule.
    pub notifier: notifier::Runtime,
    /// The fleet projection inventory, group members and the Overview share.
    pub fleet: fleet::Cache,
    /// Agents holding a wait, answered when their desired state changes.
    pub wake: wake::Registry,
}
pub type State = Arc<App>;
/// Tracked rate-limit keys per limiter partition. A full partition evicts
/// the key whose window ends soonest; it never turns a new key away.
pub const ANONYMOUS_LIMIT_KEYS: usize = 32768;
pub const PUBLIC_LIMIT_KEYS: usize = 32768;
pub const DEVICE_LIMIT_KEYS: usize = 40000;
/// Sign-in failure keys. A single instance allows 600 sign-in attempts a
/// minute, each adding at most two failure keys with 15- and 60-minute
/// windows: about 45,000 live keys at the cap, so nothing live is evicted.
pub const SIGN_IN_FAILURE_KEYS: usize = 65536;
/// Key prefixes of unauthenticated requests outside sign-in: the agent
/// listener's installer, agent downloads, the release key bundle and
/// enrollment, and invitation previews. Each namespace has a global per-minute cap behind its
/// per-address key, charged only for what the address's own budget lets
/// through. A flood from very many addresses can fill this partition with
/// its own keys; it evicts only keys of this partition, so traffic here
/// never evicts a sign-in key.
const PUBLIC_LIMIT_PREFIXES: [&str; 5] = [
    "agent-installer",
    "agent-download",
    "agent-release-keys",
    "enrollment",
    "invite-preview",
];
pub async fn initialize(settings: Settings) -> anyhow::Result<State> {
    std::fs::create_dir_all(&settings.data_dir)?;
    crypto::restrict_state(&settings.data_dir)
        .context("Cannot protect control-plane state directory")?;
    let instance_lock = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(settings.data_dir.join("instance.lock"))?;
    fs2::FileExt::try_lock_exclusive(&instance_lock)
        .map_err(|_| anyhow::anyhow!("Another control-plane instance holds this data directory"))?;
    let options = SqliteConnectOptions::new()
        .filename(settings.data_dir.join("vectory.db"))
        .create_if_missing(true)
        .journal_mode(SqliteJournalMode::Wal)
        .synchronous(SqliteSynchronous::Full)
        .foreign_keys(true)
        .busy_timeout(Duration::from_secs(5));
    let pool = SqlitePoolOptions::new()
        .max_connections(8)
        .connect_with(options)
        .await?;
    db::migrate(&pool, &sqlx::migrate!()).await?;
    // A restart or point-in-time restore must never resume a password-verified
    // pre-session capability. The exclusive instance lock makes this safe.
    sqlx::query("DELETE FROM login_challenges")
        .execute(&pool)
        .await?;
    let mfa_rows: i64 = sqlx::query_scalar("SELECT count(*) FROM user_mfa")
        .fetch_one(&pool)
        .await?;
    if mfa_rows > 0 && !settings.data_dir.join("keys/mfa-sealing.key").exists() {
        anyhow::bail!(
            "MFA records exist but the MFA sealing key is missing; restore the complete matching keys directory before starting"
        )
    }
    let keys = crypto::Keys::load(&settings.data_dir.join("keys"))
        .context("Cannot load protected control-plane keys")?;
    sqlx::query("UPDATE credentials SET signing_key_id=? WHERE signing_key_id IS NULL")
        .bind(keys.active_signing_id())
        .execute(&pool)
        .await?;
    let registered: Vec<String> = sqlx::query_scalar(
        "SELECT DISTINCT signing_key_id FROM credentials WHERE revoked=0 AND expires_at>?",
    )
    .bind(db::now())
    .fetch_all(&pool)
    .await?;
    if registered.iter().any(|id| !keys.has_signing_id(id)) {
        anyhow::bail!(
            "Active credentials reference missing manifest signing keys; restore the matching keys/signing-history directory"
        )
    }
    // A release key the server holds must be able to sign. This runs before the
    // scheduler, so the prune of sealed seeds can't have removed anything first.
    let mut conn = pool.acquire().await?;
    if let Ok(Some(fingerprint)) =
        agent_release_keys::current_seed_unavailable(&mut conn, &keys, &settings.data_dir).await
    {
        let short = &fingerprint[..16];
        tracing::warn!(
            "Agent updates are on and this server holds release key {short}, but its sealed private half can't be read or opened, so no release can be signed. Restore the keys directory from a backup that holds both the sealed key and the sealing key."
        );
    }
    drop(conn);
    let audit_exports = audit_exports::Store::initialize(&settings.data_dir)?;
    let wake = wake::Registry::new(settings.wake.clone());
    Ok(Arc::new(App {
        pool,
        writer: Mutex::new(()),
        settings,
        agent_tls: Default::default(),
        keys,
        audit_exports,
        limits: ledger::Ledger::with_capacity(ANONYMOUS_LIMIT_KEYS).into(),
        public_limits: ledger::Ledger::with_capacity(PUBLIC_LIMIT_KEYS).into(),
        device_limits: ledger::Ledger::with_capacity(DEVICE_LIMIT_KEYS).into(),
        sign_in_failures: ledger::Ledger::with_capacity(SIGN_IN_FAILURE_KEYS).into(),
        release_hashes: Default::default(),
        notifier: Default::default(),
        fleet: Default::default(),
        wake,
        agent_request_slots: tokio::sync::Semaphore::new(128),
        validation_slots: tokio::sync::Semaphore::new(2),
        instance_lock,
    }))
}
impl App {
    fn limit_partition(
        &self,
        key: &str,
    ) -> error::Result<std::sync::MutexGuard<'_, ledger::Ledger>> {
        // These namespaces are called only after mTLS registration/revocation checks.
        // Partition them from attacker-selected login email keys: an enrolled fleet
        // must not exhaust browser authentication's independent memory budget.
        let authenticated_device = key.starts_with("heartbeat:")
            || key.starts_with("artifact:")
            || key.starts_with("renew:")
            || key.starts_with("identity:")
            || key.starts_with("wait:")
            || key.starts_with("agent-release:")
            || key.starts_with("device-audit:");
        let partition = if authenticated_device {
            &self.device_limits
        } else if PUBLIC_LIMIT_PREFIXES
            .iter()
            .any(|prefix| key.starts_with(prefix))
        {
            &self.public_limits
        } else {
            &self.limits
        };
        partition.lock().map_err(|_| {
            error::ApiError::new(
                axum::http::StatusCode::INTERNAL_SERVER_ERROR,
                "INTERNAL",
                "Rate limiter unavailable",
            )
        })
    }
    /// Count an attempt against a fixed window and refuse once `maximum` have
    /// been admitted. A refused attempt is not counted: an endpoint charges
    /// the client's own budget first and a budget every client shares second,
    /// so a client that has spent its own never spends the shared one. Each
    /// partition is bounded: when full it evicts the key whose window ends
    /// soonest, so a new key is always counted, never refused.
    pub fn limit(&self, key: String, maximum: u32, window: Duration) -> error::Result<()> {
        self.limit_partition(&key)?
            .admit(&key, maximum, window)
            .map_err(|remaining| {
                error::ApiError::throttled(
                    "RATE_LIMITED",
                    format!("Too many requests. Try again in {}.", wait_text(remaining)),
                    remaining,
                )
            })
    }
    /// What `key` has counted in its current window, 0 when it has none.
    pub fn counted(&self, key: &str) -> u32 {
        self.limit_partition(key)
            .map_or(0, |mut ledger| ledger.count(key))
    }
    /// The sign-in failure ledger. A poisoned lock still yields the ledger:
    /// failure accounting must never fail open.
    pub fn sign_in_failures(&self) -> std::sync::MutexGuard<'_, ledger::Ledger> {
        self.sign_in_failures
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
    }
}
/// The TCP peer address, when the listener was served with connect info.
pub struct ClientAddress(pub Option<std::net::IpAddr>);
impl<S: Send + Sync> axum::extract::FromRequestParts<S> for ClientAddress {
    type Rejection = std::convert::Infallible;
    async fn from_request_parts(
        parts: &mut axum::http::request::Parts,
        _: &S,
    ) -> std::result::Result<Self, Self::Rejection> {
        Ok(ClientAddress(
            parts
                .extensions
                .get::<axum::extract::ConnectInfo<std::net::SocketAddr>>()
                .map(|info| info.0.ip()),
        ))
    }
}
impl App {
    /// Best-effort client address, as audits and sessions record it. Behind a
    /// trusted proxy the last X-Forwarded-For hop is the address the proxy
    /// saw; otherwise the peer. Throttles count it through `throttle_group`.
    pub fn client_key(
        &self,
        headers: &axum::http::HeaderMap,
        peer: Option<std::net::IpAddr>,
    ) -> String {
        if !self.settings.trust_proxy_headers && headers.contains_key("x-forwarded-for") {
            static WARNED: std::sync::Once = std::sync::Once::new();
            WARNED.call_once(|| {
                tracing::warn!(
                    "Requests carry X-Forwarded-For but VECTORY_TRUST_PROXY_HEADERS is off, so every client behind that proxy shares one sign-in and rate-limit budget. Set VECTORY_TRUST_PROXY_HEADERS=true only when the HTTP listener is reachable solely through the proxy."
                )
            });
        }
        let forwarded = self
            .settings
            .trust_proxy_headers
            .then(|| headers.get("x-forwarded-for")?.to_str().ok())
            .flatten()
            .and_then(|value| value.rsplit(',').next())
            .and_then(|hop| hop.trim().parse::<std::net::IpAddr>().ok());
        forwarded
            .or(peer)
            .map(|ip| ip.to_string())
            .unwrap_or_else(|| "unknown".into())
    }
}
/// The identity a client address is throttled under. One IPv6 host usually
/// holds a whole /64, so IPv6 counts per /64 prefix; IPv4 and IPv4-mapped
/// addresses count individually. Anything else passes through unchanged.
pub fn throttle_group(client: &str) -> String {
    match client.parse::<std::net::IpAddr>() {
        Ok(std::net::IpAddr::V6(v6)) => match v6.to_ipv4_mapped() {
            Some(v4) => v4.to_string(),
            None => {
                let [a, b, c, d, ..] = v6.segments();
                format!("{}/64", std::net::Ipv6Addr::new(a, b, c, d, 0, 0, 0, 0))
            }
        },
        _ => client.to_owned(),
    }
}
/// "45 seconds", "1 minute", "12 minutes".
pub fn wait_text(seconds: u64) -> String {
    if seconds < 60 {
        format!("{seconds} second{}", if seconds == 1 { "" } else { "s" })
    } else {
        let minutes = seconds.div_ceil(60);
        format!("{minutes} minute{}", if minutes == 1 { "" } else { "s" })
    }
}
