-- Acknowledgement is an operator disposition, never verified resolution.
UPDATE records SET data=json_set(data,
    '$.revision',1,'$.acknowledged',json('false'),
    '$.acknowledged_at',NULL,'$.acknowledged_by',NULL,
    '$.acknowledged_by_name',NULL,'$.acknowledgement_reason',NULL)
WHERE kind='issue';
CREATE INDEX issue_history_recent ON records(kind,COALESCE(CASE WHEN typeof(json_extract(data,'$.last_seen'))='text' AND length(json_extract(data,'$.last_seen'))<=64 AND json_extract(data,'$.last_seen') GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',json_extract(data,'$.last_seen')) ELSE NULL END,CASE WHEN typeof(json_extract(data,'$.first_seen'))='text' AND length(json_extract(data,'$.first_seen'))<=64 AND json_extract(data,'$.first_seen') GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',json_extract(data,'$.first_seen')) ELSE NULL END,CASE WHEN typeof(created_at)='text' AND length(created_at)<=64 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',created_at) ELSE NULL END) DESC,id ASC) WHERE kind='issue';
CREATE INDEX issue_history_state ON records(kind,
    CASE WHEN json_type(data,'$.resolved')='true' THEN 'resolved' WHEN json_type(data,'$.acknowledged')='true' THEN 'acknowledged' ELSE 'open' END,
    COALESCE(CASE WHEN typeof(json_extract(data,'$.last_seen'))='text' AND length(json_extract(data,'$.last_seen'))<=64 AND json_extract(data,'$.last_seen') GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',json_extract(data,'$.last_seen')) ELSE NULL END,CASE WHEN typeof(json_extract(data,'$.first_seen'))='text' AND length(json_extract(data,'$.first_seen'))<=64 AND json_extract(data,'$.first_seen') GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',json_extract(data,'$.first_seen')) ELSE NULL END,CASE WHEN typeof(created_at)='text' AND length(created_at)<=64 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',created_at) ELSE NULL END) DESC,id ASC) WHERE kind='issue';
CREATE INDEX issue_history_device_state ON records(kind,json_extract(data,'$.device_id'),
    CASE WHEN json_type(data,'$.resolved')='true' THEN 'resolved' WHEN json_type(data,'$.acknowledged')='true' THEN 'acknowledged' ELSE 'open' END,
    COALESCE(CASE WHEN typeof(json_extract(data,'$.last_seen'))='text' AND length(json_extract(data,'$.last_seen'))<=64 AND json_extract(data,'$.last_seen') GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',json_extract(data,'$.last_seen')) ELSE NULL END,CASE WHEN typeof(json_extract(data,'$.first_seen'))='text' AND length(json_extract(data,'$.first_seen'))<=64 AND json_extract(data,'$.first_seen') GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',json_extract(data,'$.first_seen')) ELSE NULL END,CASE WHEN typeof(created_at)='text' AND length(created_at)<=64 AND created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T*' THEN strftime('%Y-%m-%dT%H:%M:%fZ',created_at) ELSE NULL END) DESC,id ASC) WHERE kind='issue';
