#!/usr/bin/env python3
"""Render distribution NOTICE from checked-in, pinned upstream notice texts.

No network access or language build tools are needed. --check verifies the
source digests, dependency inputs, coverage, and exact generated NOTICE bytes.
"""
import argparse
from collections import defaultdict
import hashlib
from html.parser import HTMLParser
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'packaging/notices'

HEADER = """Vectory
Copyright 2026 Vectory contributors

Vectory is an independent open-source configuration management project for
Vector. It is not affiliated with or endorsed by Datadog, Inc. or the Vector
project. Vector and Datadog names belong to their respective owners.

THIRD-PARTY NOTICES

The following sections retain actual upstream copyright, license and notice
texts for the pinned components used by Vectory distributions. Identical texts
are printed once with every associated component listed. Different artifacts
include different subsets: browser JavaScript/Help, the Go agents and local
PKI helper, the Rust server/validator and their runtime libraries. The Rust
dependency scope conservatively includes the Linux normal/build graph; the
browser scope includes captured app/designer and rendered Help modules,
plus runtime modules embedded in the precompiled Pagefind UI.
Dependency SBOMs and declared-license inventories are supplied separately.
These materials describe inclusion and provenance, not legal clearance.

VECTOR SOURCE AND INHERITED IMAGE MATERIALS

The Vector-derived component catalog/schema and bundled component artwork
originate from Vector v0.58.0, commit
2bcad9bbb84e201dcfd58c22b1f779290101b728, under MPL-2.0. Corresponding original
source: https://github.com/vectordotdev/vector/tree/v0.58.0
Immutable source: https://github.com/vectordotdev/vector/tree/2bcad9bbb84e201dcfd58c22b1f779290101b728
Vectory modifications and reproducible catalog inputs are available in
vector-catalog/ and dashboard/src/generated/ in the matching Vectory source
release: https://github.com/416rehman/Vectory/tree/v0.2.1
Individual component artwork source URLs and SHA-256 digests are retained in
dashboard/src/assets/component-icons/provenance.json and below. Names/logos
identify their respective services; no endorsement is asserted.

The validator container redistributes the pinned official Vector 0.58.0 binary.
It retains /usr/share/vector/NOTICE, /usr/share/vector/LICENSE-3rdparty.csv and
full upstream license texts under /usr/share/vector/licenses/. Its Vector
source is available at the immutable URL above. The container also retains
installed operating-system package copyright/license files under
/usr/share/doc/ and /usr/share/common-licenses/.

PAGEFIND COMPILED SEARCH AND CORRESPONDING SOURCE

Offline Help search uses precompiled Pagefind 1.5.2 WebAssembly. Its locked
normal dependency pagefind_microjson 0.1.4 supplies GPL-3.0-only code; that
compiled search component is accompanied by the full GPLv3 text below and a
local corresponding-source archive. This does not describe Vectory's own
Apache-2.0 source as GPL-only.
Download from the installed or public Help distribution:
/help/legal/pagefind-1.5.2-source.tar.gz
Provenance and archive/WASM hashes:
/help/legal/pagefind-1.5.2-source.json
The archive contains exact upstream source commit
a2e9f40ef326f9a7926247695df25981a6f3ef4b, all 22 locked WASM package sources,
their license texts, the Snowball 3.0.0 preferred algorithm/generator source,
and optional developer rebuild instructions. Ordinary
Vectory installation uses prebuilt kits and does not require a compiler.
Primary upstream source:
https://github.com/Pagefind/pagefind/tree/a2e9f40ef326f9a7926247695df25981a6f3ef4b

Instrument Sans is bundled with its full SIL Open Font License 1.1 and original
copyright statement below; font-specific copies remain in the fonts folders.

This file is generated by packaging/generate-notices.py. Source-text versions,
URLs and SHA-256 digests are in packaging/notices/manifest.json. If an upstream
package supplied no copyright line or its published gitHead is unavailable,
the relevant provenance note below records that limit without inventing one.
"""


class PlainHTML(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts = []
        self.hidden = 0

    def handle_starttag(self, tag, attrs):
        if tag in ('style', 'script'):
            self.hidden += 1
        if tag in ('p', 'div', 'pre', 'li', 'h1', 'h2', 'h3', 'h4', 'br', 'tr'):
            self.parts.append('\n')

    def handle_endtag(self, tag):
        if tag in ('style', 'script'):
            self.hidden -= 1
        if tag in ('p', 'div', 'pre', 'li', 'h1', 'h2', 'h3', 'h4', 'tr'):
            self.parts.append('\n')

    def handle_data(self, value):
        if not self.hidden:
            self.parts.append(value)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def render(root=ROOT, data=DATA):
    manifest = json.loads((data / 'manifest.json').read_text(encoding='utf-8'))
    if manifest.get('schema') != 1:
        raise ValueError('Unsupported notice schema')
    for relative, expected in manifest['inputs'].items():
        path = root / relative
        if sha(path.read_bytes()) != expected:
            raise ValueError(f'Notice input changed: {relative}; refresh pinned source texts/scope')
    dockerfile = (root / 'deploy/Dockerfile').read_text(encoding='utf-8')
    for name, toolchain in manifest['toolchains'].items():
        if not re.search(r'^FROM\s+' + re.escape(toolchain['image']) + r'(?:\s|$)', dockerfile, re.MULTILINE):
            raise ValueError(f'Notice toolchain changed: {name}; refresh runtime notices')
    records = manifest['records']
    covered = {(r['section'], r['name'], r['version']) for r in records}
    for package in manifest['scope']['cargo-linux-normal-build']:
        if ('cargo', package['name'], package['version']) not in covered:
            raise ValueError(f"Missing Cargo notice: {package['name']}@{package['version']}")
    for section in ('npm-dashboard', 'npm-help-center'):
        scope = manifest['scope'][section]
        names = set(scope['app'] + scope['designer']) if isinstance(scope, dict) else set(scope)
        for name in names:
            if not any(s == section and n == name for s, n, _ in covered):
                raise ValueError(f'Missing browser notice: {section}/{name}')
    for package in manifest['scope'].get('npm-precompiled-help-ui', []):
        if ('npm-precompiled-help-ui', package['name'], package['version']) not in covered:
            raise ValueError(f"Missing precompiled UI notice: {package['name']}@{package['version']}")
    for section in ('go-agent', 'go-runtime', 'rust-runtime'):
        for package in manifest['scope'][section]:
            if (section, package['name'], package['version']) not in covered:
                raise ValueError(f"Missing runtime notice: {section}/{package['name']}@{package['version']}")
    groups = defaultdict(list)
    texts = {}
    for record in records:
        path = (data / record['text']).resolve()
        if not path.is_relative_to(data.resolve()) or path.suffix != '.txt':
            raise ValueError('Notice text path escaped source directory')
        raw = path.read_bytes()
        if sha(raw) != record['sha256']:
            raise ValueError(f"Notice source digest mismatch: {record['name']}/{record['file']}")
        text = raw.decode('utf-8')
        if record['file'].endswith('.html'):
            parser = PlainHTML()
            parser.feed(text)
            text = ''.join(parser.parts)
        text = re.sub(r'\n{3,}', '\n\n', text).strip() + '\n'
        digest = sha(text.encode('utf-8'))
        groups[digest].append(record)
        texts[digest] = text
    output = [HEADER.rstrip() + '\n']
    ordered = sorted(groups, key=lambda digest: min((r['section'], r['name'], r['version'], r['file']) for r in groups[digest]))
    for index, digest in enumerate(ordered, 1):
        output.append('\n' + '=' * 72 + f'\nNOTICE TEXT {index}\n' + '=' * 72 + '\n')
        for record in groups[digest]:
            output.append(f"\n[{record['section']}] {record['name']} {record['version']} | {record['file']}\n")
            output.append(f"Source: {record['source']}\n")
            if record.get('provenance_note'):
                output.append('Provenance: ' + record['provenance_note'] + '\n')
        output.append('\n' + texts[digest])
    return ''.join(output).encode('utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        expected = render()
        target = ROOT / 'NOTICE'
        if args.check:
            if target.read_bytes() != expected:
                raise ValueError('NOTICE is stale; run python packaging/generate-notices.py')
        else:
            target.write_bytes(expected)
        print(f'NOTICE verified: {len(expected)} bytes' if args.check else f'NOTICE generated: {len(expected)} bytes')
    except (OSError, ValueError, KeyError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
